### ISSUE TITLE
Surfing/Moving nodes in visual mode creates newlines

### ISSUE THREAD

**Issue by bjornevik** [ziontee113/syntax-tree-surfer#8] opened 2022-08-03 11:17 UTC
Neovim version: NVIM v0.8.0-dev-2225-gb8dcbcc73

Minimal init.lua
```lua
require("syntax-tree-surfer").setup()
local opts = { noremap = true, silent = true }

-- Select Nodes in Visual Mode
vim.keymap.set("x", "J", "<cmd>STSSelectNextSiblingNode<cr>", opts)
vim.keymap.set("x", "K", "<cmd>STSSelectPrevSiblingNode<cr>", opts)
vim.keymap.set("x", "H", "<cmd>STSSelectParentNode<cr>", opts)
vim.keymap.set("x", "L", "<cmd>STSSelectChildNode<cr>", opts)

-- Swapping Nodes in Visual Mode
vim.keymap.set("x", "<A-j>", "<cmd>STSSwapNextVisual<cr>", opts)
vim.keymap.set("x", "<A-k>", "<cmd>STSSwapPrevVisual<cr>", opts)
```

![t-rec](https://user-images.githubusercontent.com/5864000/182594742-8cb0d658-657b-4238-be73-2622f7d84273.gif)

**Comment by ziontee113** [comment] 2022-08-03 19:07
Thank you @bjornevik for opening the issue. This was caused by a recent change in `nvim-treesitter utils` module.
The issue should be fixed by now. Please update your plugin.

If any other issues show up, please let me know. Thank you :)

**Comment by bjornevik** [comment] 2022-08-03 19:17
Updated plugin and works as expected 😄 Thanks.

**Closed as completed** 2022-08-03 19:21 UTC
